#
# Copyright (C) 2012-2013, Guennadi Liakhovetski <lg@denx.de>
# (C) Copyright 2012-2013 Freescale Semiconductor, Inc.
# Copyright (C) 2014, HKC Devices
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := mx6skicad.o
obj-$(CONFIG_CMD_USB_MASS_STORAGE) += ums.o
